name: Generate Sitemap

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Sitemap
      uses: cicirello/generate-sitemap@v1.10.1
